"""initial multi tenant SaaS schema

Revision ID: b7b7711c58ab
Revises: 
Create Date: 2026-09-08 18:25:19.896256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b7711c58ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('whop_company_id', sa.String(length=100), nullable=True),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_profile', sa.String(length=30), nullable=False),
    sa.Column('daily_spend_cap_minor', sa.Integer(), nullable=False),
    sa.Column('monthly_spend_cap_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whop_company_id')
    )
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('whop_user_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_whop_user_id'), 'users', ['whop_user_id'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('whop_membership_id', sa.String(length=100), nullable=True),
    sa.Column('whop_product_id', sa.String(length=100), nullable=True),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_organization_user'),
    sa.UniqueConstraint('whop_membership_id')
    )
    op.create_index('ix_membership_access', 'memberships', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_memberships_status'), 'memberships', ['status'], unique=False)
    op.create_index(op.f('ix_memberships_whop_product_id'), 'memberships', ['whop_product_id'], unique=False)
    op.create_table('platform_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('granted_scopes', sa.JSON(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'platform', 'external_user_id', name='uq_platform_connection_identity')
    )
    op.create_index(op.f('ix_platform_connections_organization_id'), 'platform_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_platform_connections_platform'), 'platform_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_connections_status'), 'platform_connections', ['status'], unique=False)
    op.create_table('advertising_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('platform_connection_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('external_manager_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_account_id', name='uq_platform_advertising_account')
    )
    op.create_index('ix_ad_account_org_platform', 'advertising_accounts', ['organization_id', 'platform'], unique=False)
    op.create_index(op.f('ix_advertising_accounts_organization_id'), 'advertising_accounts', ['organization_id'], unique=False)
    op.create_table('oauth_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_connection_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=30), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('encryption_key_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_connection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_advertising_accounts_organization_id'), table_name='advertising_accounts')
    op.drop_index('ix_ad_account_org_platform', table_name='advertising_accounts')
    op.drop_table('advertising_accounts')
    op.drop_index(op.f('ix_platform_connections_status'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_platform'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_organization_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_memberships_whop_product_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_status'), table_name='memberships')
    op.drop_index('ix_membership_access', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_users_whop_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
